### ISSUE TITLE
Iss : Spring Data Jpa Repository Refactor 관련

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-Server#16]
rallyInfo 요청하면 최신걸로 반환해야 하는데 springDataJpa를 쓰면서 가져오는 로직이 바뀌었다 
기대대로 동작하도록 체크 필요

**Comment by ks0927** [comment]
해당내용 PR넣으신뒤에  수정해야될까요?

**Comment by Libienz** [comment]
Issue 할당 할려 했는데 샤워하면서 생각해보니 내가 약식으로 체크 가능할 듯 2번 다르게 넣고 최신것으로 가져오는지 
내가 해결하고 닫을게
