### ISSUE TITLE
Iss : ChatRoom entity 관련

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-Server#17]
매칭 정책 변경으로 ChatRoom에는 Location 필드가 필요없음 지워야 함 Dto와 얽혀 있어서 간단히 지우는 것으로 끝나지는 않을 듯

**Comment by ks0927** [comment]
음... 그러면 사라진 Location필드는 어디에서 쓰는거져

**Comment by Libienz** [comment]
https://github.com/Libienz/Spoot-Taxi-Server/blob/933df389ef788f1ff0f026d8194418edaf309aa9/src/main/java/com/capstone/smutaxi/entity/WaitingRoom.java#L11-L36

당연히 WaitingRoom에 들어가게 되지 
매칭 요청 오면 이제 채팅방에 TMA하는 것이 아니라 WaitingRoom에 TMA하게 된다 (저번 회의에서 죙일 이거 얘기했음)
이제는 WaitingRoom에 사람 꽉차면 채팅방을 생성해서 구독하도록 안내만 하기에 chatingRoom은 이제 채팅방의 역할만 가지게 된다. 
그리고 해당 작업 assign 하기 전까지 건들지 말고 ㄱㄷ 때 되면 할당 하겠음

**Comment by Libienz** [comment]
chatRoomLocation 삭제되었음 👍🏻
