### ISSUE TITLE
Iss : 채팅방 이름

### ISSUE THREAD

**Issue by ks0927** [Libienz/Spoot-Taxi-Server#27]
@Libienz 
매칭이 끝나고 채팅방을 생성할때 채팅방의 이름형식을 정해야될것같습니다.

**Comment by Libienz** [comment]
https://github.com/Libienz/Spoot-Taxi-Server/blob/3d3e9d1da6b1969e77ddf8f0fb0870c7acedce7b/src/main/java/com/capstone/smutaxi/service/matching/MatchingService.java#L144-L154

채팅방에 참가 중인 유저의 닉네임을 이어붙인 것을 chatRoomName으로 사용.
다만 유저들의 닉네임이 충분히 긴 경우 채팅방의 이름이 같이 길어지는데 프론트에서 뷰 렌더링 할 때 일정 길이 이상이면 뒤를 생략하고 "..."을 붙이도록 해야될 것 같음

**Comment by Libienz** [comment]
@ks0927 채팅 방 생성 및 유저 notify 구현 완료했습니다. PR 확인해 주세요
