### ISSUE TITLE
Iss : 배포 전 남은 작업들..!

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-Server#28]
- h2 데이터베이스 mysql로 변경
- 서버 컴퓨터 정해지고 배포되면 baseUrl 수정 (프론트도 baseUrl 수정)
- 야물 파일 수정 
    - 서버 내려가도 db clear하지 않도록 설정 변경
    - secret key와 fcm 주소 재설정 및 git ignore

**Comment by ks0927** [comment]
@Libienz 
### h2 데이터베이스 mysql로 변경

**- MySQL Installer 다운로드 (버전 8.0.34)**
https://dev.mysql.com/downloads/windows/installer/8.0.html
해당 페이지의 두번째칸 다운로드 진행(아래 사진 참고)
![image](https://github.com/Libienz/Spoot-Taxi-Server/assets/63335224/383425fd-198f-4dc3-b101-11a392b96b61)

- setup type 을 full로 선택하여 다 다운로드한다.(아래 사진 참고)
![image](https://github.com/Libienz/Spoot-Taxi-Server/assets/63335224/4c2c6f47-2fdb-4730-a565-1afb7f43c048)

계속 next 와 excute를 누르며 진행

- password 보안성 체크필드에서 아래 Lagacy선택(아래 사진 참고)
![image](https://github.com/Libienz/Spoot-Taxi-Server/assets/63335224/11d6f374-f262-46ba-bf00-878c03520d3a)

- root의 비밀번호를 정하는데 잊어버리면 골치아프니 **꼭** 기억하자

이후는 문제없이 계속 진행하면 MySQL을 다운로드 한것.

1. 윈도우+ R 버튼을 눌러 실행창을 연뒤 services.msc를 입력한다.
2. 서비스 창에서 MySQL80 서비스가 있다면 제대로 설치되었다는 의미(실행중 이라면 서버실행중인것)


cmd에서 MySQL을 실행되게 하려면 환경 변수에 Path를 등록해줘야한다.

1. MySQL 실행파일이 있는 bin 폴더까지의 경로를 Ctrl + C (복사 해둔다.)
 경로: C:\Program Files\MySQL\MySQL Server 8.0\bin (예시)
 
2. 윈도우 + R 버튼을 눌러 실행창을 연뒤 SystemPropertiesAdvanced를 입력한다.
3. 환경 변수(N)... 을 클릭한다.
4. 어느 누구나 사용할 수 있는 공통의 시스템 변수인 시스템 변수(S)의 Path를 편집한다.
5. 새로 만들기(N) 을 경로를 붙여넣는다.

이제부턴 cmd에서 MySQL 로그인할 때는 mysql -h 주소 -u 유저명 -p password 를 같이 입력하면된다.

**이제 Workbench 를 사용해보자.**

1. MySQL Workbench 8.0 CE 를 실행한다.
2. +버튼을 눌러서 Setup New Connection(새 커넥션)을 생성한다.
3. Connection Name을 정한다.
4. 마지막으로 Test Connection 을 클릭한다음 Successfully... 라는 문구가 뜨면 정상적으로 Connection이 생성된것이다. 그리고 Ok를 눌러 MySQL을 생성한다.
5. 새로생긴 Connection을 더블클릭해서 실행한뒤 비밀번호를 입력한다.

지금까지의 내용은
 https://velog.io/@yongseok0419/DatabaseMySQL-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95
해당 링크를 참조했다.

**이제 스키마를 만들어보자**

하단부에 Schemas를 누른뒤 좌측에 sys스키마(Schema)를 우클릭하면 createSchema라는 항목이 있는데
여기서 프로젝트와 연동할 스키마를 미리 생성하자.
utf8에 utf8_bin 으로 설정한뒤 진행하면 스키마가 잘생성된다.

해당 스키마의 이름을기억해두자.

**이제 MySQL 설정은 끝났다. 이제 스프링부트에서 설정을 해보자.**

build.gradle에 	implementation 'mysql:mysql-connector-java'를 추가한다.

yml에 
  datasource:
    url: jdbc:mysql://localhost:3306/스키마이름
    username: 사용자
    password: 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

를 추가하면 된다.

**Comment by Libienz** [comment]
로컬 환경 mysql로 db 이식 완료 @ks0927 👍🏻
