### ISSUE TITLE
Iss: 서버 성능 튜닝 (N+1문제 해결) 

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-Server#47]
### api/chatrooms/{roomId}/participants/{participantId} (DELETE)
- 삭제 연관관계 메서드를 필요 

### api/chatrooms/ (GET)
- chatParticipantList까지만 페치조인으로 일대다 컬렉션 조회 최적화 

### api/chatrooms/{roomId}/messages (GET)
- 챗룸과 messages 일대다 컬렉션 페치조인 최적화 
- chatParticipantId는 따로 쿼리를 날려서 해결  

### api/match/request
- 이미 내 아이디로 된 매칭이 있는지 확인하는 부분 최적화(by 페치 조인 혹은 where 파라미터)
- waitingRoom돌기위해서 가져올때 사이즈 체크하는 부분의 쿼리를 줄이기 위해서 waitingRoom과 wru를 페치조인 

### api/match/cancel-request
- waitingRoom가져올 때 wru 페치조인 최적화해서 가져오기
- waitingRoom에서 유저를 지울때도 페치조인 걸고 해결하기 

### api/rally-information
- getRecentRallyInfo 메서드 탑 row 하나 가져오는 걸로 수정

**Comment by ks0927** [comment]
### **해결 완료**

### api/chatrooms/{roomId}/participants/{participantId} (DELETE)
- chatparticipant를 delete하면 User나 ChatRoom 객체 상태와 DB 상태가 일치하지 않아 혼란을 초래할수있음
  - 따라서 삭제 연관관계 메서드 remove 추가
- remove를 사용할때 chatroom에서 user와 chatparticipant를 get으로 접근하기때문에 추가쿼리가 나감
  - 따라서 chatroom과 user 와 chatparticipant를 fetch join해서 쿼리 최적화


### api/chatrooms/ (GET)
- user와 chatParticipant를 페치조인하여  일대다 컬렉션 조회 최적화



### api/chatrooms/{roomId}/messages (GET)

- chatroom 과 message를 페치조인하여 일대다 컬렉션 조회 최적화
- chatParticipantId는 findByUserEmailAndChatRoomId를 통해 특정user와 chatroom일때의 chatparticipant를 구한다.

**Comment by Libienz** [comment]
> ### **해결 완료**
> ### api/chatrooms/{roomId}/participants/{participantId} (DELETE)
> * chatparticipant를 delete하면 User나 ChatRoom 객체 상태와 DB 상태가 일치하지 않아 혼란을 초래할수있음
>   
>   * 따라서 삭제 연관관계 메서드 remove 추가
> * remove를 사용할때 chatroom에서 user와 chatparticipant를 get으로 접근하기때문에 추가쿼리가 나감
>   
>   * 따라서 chatroom과 user 와 chatparticipant를 fetch join해서 쿼리 최적화
> 
> ### api/chatrooms/ (GET)
> * user와 chatParticipant를 페치조인하여  일대다 컬렉션 조회 최적화
> 
> ### api/chatrooms/{roomId}/messages (GET)
> * chatroom 과 message를 페치조인하여 일대다 컬렉션 조회 최적화
> * chatParticipantId는 findByUserEmailAndChatRoomId를 통해 특정user와 chatroom일때의 chatparticipant를 구한다.

고생해따 다음엔 초반 설계부터 얻은 교훈 바탕으로 빡세게 들가보자잉 나는 오늘 내일 중으로 작업 착수해볼게

**Comment by Libienz** [comment]
### api/match/request

- 이미 내 아이디로 된 매칭이 있는지 확인하는 부분 최적화
https://github.com/Libienz/Spoot-Taxi-Server/blob/209b0db96cc14d95ad6fa65b15aed939ce0f3b6c/src/main/java/com/capstone/smutaxi/repository/WaitingRoomUserRepositoryImpl.java#L23-L31


waitingRoom돌기위해서 가져올때 사이즈 체크하는 부분의 쿼리를 줄이기 위해서 waitingRoom과 wru를 페치조인
api/match/cancel-request
waitingRoom가져올 때 wru 페치조인 최적화해서 가져오기
waitingRoom에서 유저를 지울때도 페치조인 걸고 해결하기
api/rally-information
getRecentRallyInfo 메서드 탑 row 하나 가져오는 걸로 수
